import Sidebar from '@/components/Sidebar/Sidebar';
import Charts from '@/components/Charts/page'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className="antialiased">
        <Sidebar>
          <Charts/>
          {children}
        </Sidebar>
      </body>
    </html>
  );
}
