// app/layout.tsx
import Sidebar from "@/components/Sidebar/Sidebar"; // Asegúrate de importar el Sidebar correctamente
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen`}
      >
        {/* Sidebar visible para todas las páginas */}
        
        {/* Contenido principal */}
        <main className="flex-1 bg-gray-100">
          {children}
        </main>
      </body>
    </html>
  );
}
